#!/usr/bin/php
<?php

require_once 'vendor/autoload.php';
require_once 'functions.php';


/**
 * ./cli.php --book=example/example.php --task=ping --env=test --role=app
 */
$request = getopt('', ['book:','task:','env:', 'role:', 'parallel:']);

$book = isset($request['book']) && is_file($request['book']) ? $request['book'] : null;
$task = isset($request['task']) ? $request['task'] : 'info';
$env = isset($request['env']) ? (array) explode(',', trim($request['env'])) : [];
$role = isset($request['role']) ? (array) explode(',', trim($request['role'])) : [];
$parallel = isset($request['parallel']) ? (int) $request['parallel'] : 1;

if ($book) {
    $paths[] = $book;
}
$paths[] = '../satisfy.php';
$paths[] = '../../satisfy.php';
$paths[] = '../../../satisfy.php';
$paths[] = '../../../../satisfy.php';
$paths[] = '../../../../../satisfy.php';

foreach ($paths as $path) {
    if (is_file($path)) {
        $book = $path;
        require_once $path;
        break;
    }
}
satisfy()->writeln(' ► Book   : ' . $book);
satisfy()->writeln(' ► Task   : ' . $task);
satisfy()->writeln(' ► Role   : ' . implode(', ', $role));
satisfy()->writeln(' ► Env    : ' . implode(', ', $env));

play($task, $env, $role, $parallel);